blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('tag/<str:slug>/', views.tag_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('search/<str:q>/', views.PostSearch.as_view()),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('', include('single_pages.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'
        
    class Meta:
        verbose_name_plural = 'Categories'
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'
        
class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = MarkdownxField()
    
    
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    
    tags = models.ManyToManyField(Tag, blank=True)
    
    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
    def get_content_markdown(self):
        return markdown(self.content)
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/212/00c5671ced17e6e3/svg/{self.author.email}'
            
    def __str__(self):
        return f'{self.author}::{self.content}'
    
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
# Create your views here.
class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context
    
class PostDetail(DetailView):
    model = Post
    
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context
    
def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
        
    return render(
        request,
        'blog/post_list.html',
        {
            'post_list' : post_list,
            'categories' : Category.objects.all(),
            'no_category_post_count' : Post.objects.filter(category=None).count(),
            'category' : category,
        }
    )

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list' : post_list,
            'categories' : Category.objects.all(),
            'no_category_post_count' : Post.objects.filter(category=None).count(),
            'tag' : tag,
        }
    )

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (self.request.user.is_superuser or self.request.user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')
                
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')
        
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']
    
    template_name = 'blog/post_update_form.html'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and (request.user == self.get_object().author):
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
            
    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)
        return context
    
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response
    
def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
            
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied
        
class PostSearch(PostList):
    paginate_by = None
    
    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link
            href="{% static 'blog/bootstrap/bootstrap.min.css' %}"
            rel="stylesheet"
            media="screen"
        />
        <script src="https://kit.fontawesome.com/d99b8e64c6.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include 'blog/navbar.html' %}
        <div class="container my-3">
            <div class="row">
                <div class="col-md-8 col-lg-9" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                </div>

                <div class="col-md-4 col-lg-3">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input
                                    class="form-control"
                                    type="text"
                                    placeholder="Enter search term..."
                                    aria-label="Enter search term..."
                                    aria-describedby="button-search"
                                    id="search-input"
                                />
                                <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost();">
                                    Go!
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4" id="categories-card">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <ul class="ms-3">
                                    {% for category in categories %}
                                    <li><a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a></li>
                                    {% endfor %}
                                    <li><a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            function searchPost(){
                let searchValue = document.getElementById('search-input').value.trim();
                if (searchValue.length > 1){
                    location.href="/blog/search/"+searchValue+"/";
                }
                else
                    alert('검색어('+searchValue+')가 너무 짧습니다.');
            };
            
            document.getElementById('search-input').addEventListener('keyup', function(event){
                if(event.key === 'Enter'){
                    searchPost();
                }
            });
        </script>
        {% include 'blog/footer.html' %}

        <!-- Bootstrap core JS-->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <title>{% block head_title %}Blog{% endblock %}</title>
        <link
            href="{% static 'blog/bootstrap/bootstrap.min.css' %}"
            rel="stylesheet"
            media="screen"
        />
        <script src="https://kit.fontawesome.com/d99b8e64c6.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include 'blog/navbar.html' %}
        <div class="container my-3">
            <div class="row">
                <div class="col-12" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                </div>
            </div>
        </div>

        {% include 'blog/footer.html' %}

        <!-- Bootstrap core JS-->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
<h1>Edit comment</h1>
<hr/>
<form method="post" id="comment-form">{% csrf_token %}
    {{ form | crispy }}
    <br/>
    <button type="submit" class="btn btn-primary float-end">
        Submit
    </button>
</form>
{{ form.media }}
{% endblock %}

blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Kim Eun-Jong 2021</p>
    </div>
</footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>Blog</title>
    </head>
    <body>
        <h1>
            Blog
        </h1>
        {% for p in post_list %}
        <hr/>
        <h2>
            <a href="{{ p.get_absolute_url }}">{{ p.title }}</a>        
        </h2>
        <h4>
            {{ p.created_at }}
        </h4>
        <p>
            {{ p.content }}
        </p>
        {% endfor %}
    </body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Navbar</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about_me/">About Me</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.socialaccount_set.all.0.get_avatar_url %}
                            <img class="rounded-circle" width="25px" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="">
                        {% else %}
                            <img class="rounded-circle" width="25px" src="https://doitdjango.com/avatar/id/212/00c5671ced17e6e3/svg/{{ user.email }}">
                        {% endif %}
                        &nbsp;
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/accounts/logout/">Log Out</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" data-bs-toggle="modal" data-bs-target="#loginModal" href="#"
                        >Sign In</a
                    >
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Modal -->
<div
    class="modal fade"
    id="loginModal"
    tabindex="-1"
    aria-labelledby="loginModalLabel"
    aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">
                    <i class="fas fa-sign-in-alt"></i>&nbsp; Log In
                </h5>
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                ></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 d-grid gap-2">
                        <a role="button" href="{% provider_login_url 'google' %}" class="btn btn-outline-primary btn-sm w-100">
                            <i class="fab fa-google"></i>
                            &nbsp; Sign in with Google
                        </a>
                        <a role="button" href="/accounts/login/" class="btn btn-outline-dark btn-block btn-sm w-100">
                            <i class="fab fa-envelope"></i>
                            &nbsp; Sign in with E-mail
                        </a>
                    </div>
                    <div class="col-md-6 d-grid gap-2">
                        <button type="button" class="btn btn-outline-primary btn-sm w-100">
                            <i class="fab fa-facebook"></i>
                            &nbsp; Sign in with Facebook
                        </button>
                        <a role="button" href="/accounts/signup/" class="btn btn-outline-dark btn-block btn-sm w-100">
                            <i class="fab fa-envelope"></i>
                            &nbsp; Sign up with E-mail
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %} {{ post.title }} - Blog {% endblock %}
{% block main_area %}
<div id="post-area">
    <!-- Post content-->
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <span class="badge bg-secondary float-end"
                >{% if post.category %}{{ post.category }}{% else %}미분류{% endif %}</span
            >
            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
            {% if post.hook_text %}
            <h5 class="text-muted">
                {{ post.hook_text }}
            </h5>
            {% endif %}
            <!-- Post meta content-->
            <hr />
            <div class="text-muted fst-italic mb-2">
                {{ post.created_at }} &nbsp;&nbsp;by {{ post.author | upper }} 
                {% if user.is_authenticated and user == post.author %}
                <a
                    class="btn btn-info btn-sm float-end"
                    href="/blog/update_post/{{ post.pk }}/"
                    role="button"
                >
                    <i class="fas fa-pen"></i> Edit Post
                </a>
                {% endif %}
            </div>
            <hr />
        </header>
        <!-- Preview image figure-->
        <figure class="mb-4">
            {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="..." />
            {% else %}
            <img
                class="img-fluid rounded"
                src="https://picsum.photos/seed/{{ post.id }}/800/400"
                alt="..."
            />
            {% endif %}
        </figure>
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">
                {{ post.get_content_markdown | safe }}
            </p>
            {% if post.tags.exists %}
            <i class="fas fa-tag"></i>
            {% for tag in post.tags.all %}
            <a href="{{ tag.get_absolute_url }}"
                ><span class="badge bg-warning text-dark">{{ tag }}</span></a
            >
            {% endfor %}
            <br />
            <br />
            {% endif %}
            {% if post.file_upload %}
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-success" role="button">
                Download: {% if post.get_file_ext == 'csv' %}
                <i class="fas fa-file-csv"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                <i class="fas fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' %}
                <i class="fas fa-file-word"></i>
                {% else %}
                <i class="fas fa-file"></i>
                {% endif %} {{ post.get_file_name }}
            </a>
            {% endif %}
        </section>
    </article>
</div>
<div id="comment-area">
    <!-- Comments section-->
    <section class="mb-5">
        <div class="card bg-light">
            <h5 class="card-header">
                Leave a Comment:
            </h5>
            <div class="card-body">
                <!-- Comment form-->
                {% if user.is_authenticated %}
                <form
                    class="mb-4"
                    id="comment-form"
                    method="POST"
                    action="{{ post.get_absolute_url }}new_comment/"
                >
                    <div class="form-group">
                        {% csrf_token %} {{ comment_form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">
                        Submit
                    </button>
                </form>
                {% else %}
                <a
                    role="button"
                    class="btn btn-outline-dark btn-block btn-sm"
                    href="#"
                    data-toggle="modal"
                    data-target="#loginModal"
                >
                    Log in and leave a comment
                </a>
                {% endif %}
                <!-- Single comment-->
                {% if post.comment_set.exists %} 
                {% for comment in post.comment_set.iterator %}
                <div class="d-flex media" id="comment-{{ comment.pk }}">
                    <img
                        class="me-3 rounded-circle"
                        src="{{ comment.get_avatar_url }}"
                        alt="{{ comment.author }}"
                        width="60px"
                        height="60px"
                    />
                    <div class="flex-grow-1">
                    {% if user.is_authenticated %} 
                    {% if comment.author == user or user.is_superuser %}
                    <div class="media-body">
                        <div class="float-end">
                            <a
                                role="button"
                                class="btn btn-sm btn-info"
                                id="comment-{{ comment.pk }}-update-btn"
                                href="/blog/update_comment/{{ comment.pk }}/"
                            >
                                edit
                            </a>
                            <a
                                role="button"
                                href="#"
                                id="comment-{{ comment.pk }}-delete-modal-btn"
                                class="btn btn-sm btn-danger"
                                data-bs-toggle="modal"
                                data-bs-target="#deleteCommentModal-{{ comment.pk }}"
                            >
                                delete
                            </a>
                        </div>

                        <!-- Modal -->
                        <div
                            class="modal fade"
                            id="deleteCommentModal-{{ comment.pk }}"
                            tabindex="-1"
                            role="dialog"
                            aria-labelledby="deleteCommentModalLabel"
                            aria-hidden="true"
                        >
                            <div class="modal-dialog" rold="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">
                                            Are you Sure?
                                        </h5>
                                        <button
                                            type="button"
                                            class="btn-close"
                                            data-bs-dismiss="modal"
                                            aria-label="Close"
                                        >
                                            <span area-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <del>{{ comment | linebreaks }}</del>
                                    </div>
                                    <div class="modal-footer">
                                        <button
                                            type="button"
                                            class="btn btn-secondary"
                                            data-bs-dismiss="modal"
                                        >
                                            Cancel
                                        </button>
                                        <a
                                            role="button"
                                            class="btn btn-danger"
                                            href="/blog/delete_comment/{{ comment.pk }}/"
                                            >Delete</a
                                        >
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %} 
                        {% endif %}
                        <div class="ms-0">
                            <div>
                                <div class="fw-bold">
                                    {{ comment.author.username }} &nbsp;&nbsp;<small
                                        class="text-muted"
                                        >{{ comment.created_at }}</small
                                    >
                                </div>
                                <p>
                                    {{ comment.content | linebreaks }}
                                </p>
                                {% if comment.created_at != comment.updated_at %}
                                <p class="text-muted float-end">
                                    <small>Updated: {{ comment.updated_at }}</small>
                                </p>
                                {% endif %}
                                <br />
                                <br/>
                            </div>
                        </div>
                    </div>
                    </div>
                {% endfor %}
                </div>
                {% endif %}
            </div>
            <hr />
        </div>
    </section>
</div>
{% endblock %}

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>{{ post.title }} - Blog</title>
    </head>
    <body>
        <nav>
            <a href="/blog/">Blog</a>
        </nav>
        <h1>
            {{ post.title }}
        </h1>
        <h4>
            {{ post.created_at }}
        </h4>
        <p>
            {{ post.content }}
        </p>
        <hr/>
        <h3>
            댓글 자리
        </h3>
    </body>
</html>